spring.datasource:
  url: jdbc:postgresql://localhost:5001/pda
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  database:
    type: postgres
    table-prefix: order-process